name: booky

services: 
  postgres: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=nattobean
      - POSTGRES_PASSWORD=nattopostgres
      - POSTGRES_DB=app_db
    command: ["postgres", "-c", "log_statement=all"]


  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://nattobean:nattopostgres@postgres/app_db
      - ROCKET_DATABASES={postgres={url=postgres://nattobean:nattopostgres@postgres/app_db}}
    ports: 
      - 8080:8080
    volumes:
      - ./:/app/